"""empty message

Revision ID: 2b6340c1abeb
Revises: c5a599104381
Create Date: 2017-07-04 14:18:17.573515

"""

# revision identifiers, used by Alembic.
revision = '2b6340c1abeb'
down_revision = 'c5a599104381'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('caretakers', sa.String(length=64), nullable=True),
    sa.Column('vet', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dogs_default'), 'dogs', ['default'], unique=False)
    op.add_column(u'users', sa.Column('dogs', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'dogs')
    op.drop_index(op.f('ix_dogs_default'), table_name='dogs')
    op.drop_table('dogs')
    # ### end Alembic commands ###
