"""empty message

Revision ID: b7b041f6a529
Revises: 2b6340c1abeb
Create Date: 2017-07-16 08:32:11.160482

"""

# revision identifiers, used by Alembic.
revision = 'b7b041f6a529'
down_revision = '2b6340c1abeb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vets')
    # ### end Alembic commands ###
